"""Add entities data to tasks table

Revision ID: b08333d88828
Revises: a07222c77727
Create Date: 2025-01-20 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b08333d88828'
down_revision = 'a07222c77727'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('entities_data', sa.JSON(), nullable=True))
    op.add_column('tasks', sa.Column('entities_extracted_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'entities_extracted_at')
    op.drop_column('tasks', 'entities_data')
    # ### end Alembic commands ###